import asyncio
import json
from websockets.exceptions import ConnectionClosedOK
from websockets.exceptions import ConnectionClosedError
import numpy as np
import random

from os import path 
path_to_dat = path.abspath(path.join(path.dirname(__file__), 'test_data/test-flight-2026-March-modified.csv'))

import csv

from utility import get_pitch_yaw


#Autogenerated test data
async def rocketry_data_test_handler(websocket):
    print("entering test loop")
    x_curr = 0.0;
    y_curr = 0.0;
    z_curr = 0.0;
    alt_curr = 0.0;

    while True:
        try:
            data = {
                "alt": 0,
                "velocity": random.uniform(1, 10),
                "position": {random.uniform(1, 10),
                            random.uniform(1, 10),
                            random.uniform(1, 10)},
            }
            print("sending", data, flush = True)
            await websocket.send(json.dumps(data))

            await asyncio.sleep(1)
        except ConnectionClosedError:
            print ("ERR", flush = True)
            break

"""
#Simulates test data based on rocketry data, will run until all csv rows are transmitted
async def rocketry_data_file_test_handler(websocket):
    print ("RUNNING", flush = True)
    
    with open(path_to_dat, 'r', newline='') as csvfile:
        dat = []
        reader = csv.DictReader(csvfile, skipinitialspace=True ,delimiter=',', quotechar='|')
        for row in reader:
            dat.append(row);

    total_sleep_time = 0
    sleep_offset = 0


    launch_coord = None
    prev_coord = None
    roll = 0


        
    while len(dat) > 2:
        pitch = 0
        yaw = 0

        try:
            row = dat.pop(0)

            if (row['longitude'] != "-77.1476655"): #crackhead data keeps jumping to end point for some reason
                #if (launch_coord != None):
                #    pitch, yaw = get_pitch_yaw(launch_coord, [float(row['latitude']), float(row['altitude']), float(row['longitude'])])
                if (prev_coord != None):
                    temp_pitch, temp_yaw = get_pitch_yaw(prev_coord, [float(row['latitude']), float(row['longitude']), float(row['altitude']) ])
                    
                    if (prev_coord[2] != float(row['altitude'])):
                        pitch = temp_pitch

                    #if (prev_coord[0] != float(row['latitude']) or prev_coord[1] != float(row['longitude'] )):
                    yaw = temp_yaw
                    

                data = {
                    "alt": float(row['altitude']),
                    "velocity": float(row['speed']),
                    "timestamp": float(row['time']),
                    "acceleration": float(row['acceleration']),
                    "pressure": float(row['pressure']),
                    "state": (row['state_name']).strip(),
                    "position": {'x': float(row['latitude']),
                                'y': float(row['altitude']),
                                'z': float(row['longitude'])},
                    "quaternion": {'x': 0,
                    'y': 0.707,
                    'z': -0.707,
                    'w': 0},

                    "orientation": {'pitch': pitch,
                    'roll': roll,
                    'yaw': yaw,
                    },

                    "battVolt": float(row['battery_voltage']),
                    "drogVolt": float(row['drogue_voltage']),
                    "temp": float(row['temperature']),
                    "mainVolt": float(row['main_voltage']),
                }
                #print("sending (Sleeptime): " + str(total_sleep_time) )

                if (launch_coord == None):
                    launch_coord = [float(row['latitude']), float(row['longitude']), float(row['altitude'])]
                prev_coord = [float(row['latitude']), float(row['longitude']), float(row['altitude'])]
            
            if (roll > 360):
                roll = 0
            else:
                roll += 1

                    

            #default sleep time
            sleeptime = 0.1
            #ignore negative time
            if (float(row['time']) < 0):
                sleeptime = 0.5
                pass
            if (dat.count != 1):
                if (float(dat[0]['time']) - float(row['time']) == 0):
                    data['timestamp'] = str(float(row['time']) + sleep_offset)
                    sleep_offset += 0.5

                    #default sleep time
                    sleeptime = 0.1
                else:
                    data['timestamp'] = str(float(row['time']) + sleep_offset)
                    sleeptime = float(dat[0]['time']) - float(row['time']) 
                    total_sleep_time += sleeptime 

            #print(data)
            await websocket.send(json.dumps(data))

            await asyncio.sleep(sleeptime)
        except ConnectionClosedOK:
            print("CONNECTION (DASHBOARD) CLOSED", flush = True)
            break

    print ("END OF TRANMISSION", flush = True)
"""

#Simulates test data based on rocketry data, will run until all csv rows are transmitted (FAKES LONGITUDE AND LATITUDE CAUSE TEST DATA IS SHIT)
async def rocketry_data_file_test_handler(websocket):
    print ("RUNNING", flush = True)
    
    with open(path_to_dat, 'r', newline='') as csvfile:
        dat = []
        reader = csv.DictReader(csvfile, skipinitialspace=True ,delimiter=',', quotechar='|')
        for row in reader:
            dat.append(row);

    total_sleep_time = 0
    sleep_offset = 0


    launch_coord = None
    prev_coord = None
    roll = 0


    missed_packets = 0 
    total_packets = 0

    #FAKED STUFF
    time_step = 0
    time_step_threshold = 5
    longitude = -77.1476655
    latitude = 42.6954034

    alt_time_step = 0
    alt = 0

    pitch_time_step = 0
    pitch = 0

    roll_time_step = 0
    roll = 0

    delta_long = -(random.randint(1, 10))/100000
    delta_lat = (random.randint(1, 10))/100000

    while len(dat) > 2:
        total_packets += 1
        #pitch = 0
        yaw = 0

        try:
            row = dat.pop(0)

            if (prev_coord != None):
                #pitch is broke asf from this function btw
                temp_pitch, temp_yaw = get_pitch_yaw( [latitude, longitude, alt ], prev_coord)
                #print (temp_pitch)

                yaw = -temp_yaw + 86 # + 86 cause its for some reason tangent to line, -temp_yaw cause yess
                #pitch = temp_pitch
                

            """
            data = {
                "alt": alt,
                "velocity": float(row['speed']),
                "timestamp": float(row['time']),
                "acceleration": float(row['acceleration']),
                "pressure": float(row['pressure']),
                "state": (row['state_name']).strip(),
                "position": {'x': latitude,
                            'y': alt,
                            'z': longitude},
                "quaternion": {'x': 0,
                'y': 0.707,
                'z': -0.707,
                'w': 0},

                "orientation": {'pitch': pitch,
                'roll': roll,
                'yaw': yaw,
                },

                "battVolt": float(row['battery_voltage']),
                "drogVolt": float(row['drogue_voltage']),
                "temp": float(row['temperature']),
                "mainVolt": float(row['main_voltage']),
            }
            """

            data = {
                "timestamp": float(row['time']),
                "state": 'main',

                #LAT, LONG, ALT
                "position": {'x': latitude,
                            'y': alt,
                            'z': longitude},
                "alt": alt,           

                #UNUSED IGNORE
                "quaternion": {'x': 0,
                'y': 0.707,
                'z': -0.707,
                'w': 0},

                #GYRO X/Y/Z (ASSUMING CONVERTED TO PITCH/ROLL/YAW)
                "orientation": {
                'pitch': pitch,
                'roll': roll,
                'yaw': yaw,
                },
                
                #ACCELERATION AXIS X/Y/Z
                "acceleration_axis": {
                    'x': float(row['acceleration']),
                    'y': float(row['acceleration']),
                    'z': float(row['acceleration']),
                },

                #ACCELERATION AXIS X/Y/Z
                "gyro_axis": {
                    'x': float(row['acceleration']),
                    'y': float(row['acceleration']),
                    'z': float(row['acceleration']),
                },

                #get the magnitude of acceleration
                "acceleration": float(row['acceleration']),

                #MISC DATA POINTS
                "battVolt": float(row['battery_voltage']),
                "temp": float(row['temperature']),
                "velocity": float(row['speed']),
                "pressure": float(row['pressure']),

                #RADIO STUFF
                "radio_info": {
                    "rssi": 10,
                    "snr": 15,
                    "freqError": 17,
                    "callsign": "TEST123CALL",
                    "totalPackets": total_packets,
                    "missedPackets": missed_packets
                },

                #32 Bit Status Check
                "statusBits": int(4294967295),

                #NOT USED
                "drogVolt": float(-1),
                "mainVolt": float(-1),
            }
            #print("sending (Sleeptime): " + str(total_sleep_time) )



            if (launch_coord == None):
                launch_coord = [latitude, longitude, alt]
            prev_coord = [latitude, longitude, alt]


            longitude += delta_long
            latitude += delta_lat

            
            alt_time_step += 0.05
            pitch_time_step += 0.05
            roll_time_step += 0.05
            #print ("pitch is: " + pitch)
            alt = round((np.sin(alt_time_step)*150 + 300))
            pitch = round(np.sin(pitch_time_step)*45)
            roll = round(np.sin(roll_time_step)*45)
            #print (alt)

            time_step += 1
            if (time_step == time_step_threshold):
                time_step = 0
                delta_long = -(random.randint(1, 10))/100000
                delta_lat = (random.randint(1, 10))/100000
            


                    

            #default sleep time
            total_sleep_time += 1
            data['timestamp'] = str(total_sleep_time)

            #print(data)
            await websocket.send(json.dumps(data))

            await asyncio.sleep(0.75)
        except ConnectionClosedOK:
            print("CONNECTION (DASHBOARD) CLOSED", flush = True)
            break

    print ("END OF TRANMISSION", flush = True)

    
#test run of test data csv to console 
async def rocketry_data_csv_test_console():
    with open('test_data/test-flight-2026-March.csv', 'r', newline='') as csvfile:
        dat = []
        reader = csv.DictReader(csvfile, skipinitialspace=True ,delimiter=',', quotechar='|')
        for row in reader:
            dat.append(row);
    
    #print first x rows of data to check csv
    for idx, row in enumerate(dat):
        if (idx < 30):
            print (dat[idx]['speed'], flush = True)
    #print("reading .csv", dat)
    