
import asyncio
import json
from websockets.asyncio.server import serve
from websockets.exceptions import ConnectionClosedOK
from websockets.exceptions import ConnectionClosedError
from websockets.exceptions import ConnectionClosed
from websockets.exceptions import ConcurrencyError
import random

from os import path 
path_to_dat = path.abspath(path.join(path.dirname(__file__), 'test_data/test-flight-2026-March-modified.csv'))

import csv
import sys

from radio_handler import radio_handler as radio_handle

async def kill_command():
    await asyncio.get_event_loop().run_in_executor(None, lambda: input("Enter something: "))
    sys.exit()

async def main():
    #async with serve(rocketry_data_file_test_handler, "localhost", 8765) as server:
    async with serve(state_handler, "localhost", 8765) as server:
        loop = asyncio.get_event_loop()
        loop.create_task(kill_command())

        await server.serve_forever()

        #input('Press ANY to exit')
        #sys.exit()

            

async def state_handler(websocket):
    #await rocketry_data_file_test_handler(websocket)
    print("SERVER CONNECTED TO GUI", flush = True);
    print ("AWAITING INITIALIZATION INPUT: ############################", flush = True)
    running = False

    process = None

    try:
        async for message in websocket:   
            print ("MESSAGE RECIEVED:", flush = True)


            if (running == False): #do not allow launching more handlers on same connection
                print ("(FIRST MESSAGE: \"" + message + "\") SERVER INITIALIZING TELEMETRY MODE:", flush = True)
                match message:
                    case "demo":
                        print ("TELEMETRY IN DEMO MODE ----------", flush = True)
                        running = True
                        await rocketry_data_file_test_handler(websocket)
                        
                    case "live":
                        print ("TELEMETRY IN LIVE MODE ----------", flush = True)
                        running = True
                        await radio_handle(websocket)
                    case _:
                        print ("INVALID CASE", flush = True)
            else:
                print ("(SECOND+ MESSAGE: \"" + message + ") SERVER ALREADY RUNNING", flush = True)
    except ConnectionClosedError:
        print ("ERROR", flush = True)
    except ConnectionClosedOK:
        print ("CLOSED GRACEFULLY", flush = True)
    except ConnectionClosed:
        print ("GENERIC CLOSE", flush = True)

    #if (process != None):
    #    print("async routine is running")
    #    process.close()
    print("Connection ENDED", flush = True);

#Autogenerated test data
async def rocketry_data_test_handler(websocket):
    print("entering test loop")
    x_curr = 0.0;
    y_curr = 0.0;
    z_curr = 0.0;
    alt_curr = 0.0;

    while True:
        try:
            data = {
                "alt": 0,
                "velocity": random.uniform(1, 10),
                "position": {random.uniform(1, 10),
                            random.uniform(1, 10),
                            random.uniform(1, 10)},
            }
            print("sending", data, flush = True)
            await websocket.send(json.dumps(data))

            await asyncio.sleep(1)
        except ConnectionClosedError:
            print ("ERR", flush = True)
            break

#Simulates test data based on rocketry data, will run until all csv rows are transmitted
async def rocketry_data_file_test_handler(websocket):
    print ("RUNNING", flush = True)
    
    with open(path_to_dat, 'r', newline='') as csvfile:
        dat = []
        reader = csv.DictReader(csvfile, skipinitialspace=True ,delimiter=',', quotechar='|')
        for row in reader:
            dat.append(row);

    total_sleep_time = 0
    sleep_offset = 0
    while len(dat) > 2:
        try:
            row = dat.pop(0)

            if (row['longitude'] != "-77.1476655"): #crackhead data keeps jumping to end point for some reason
                data = {
                    "alt": float(row['altitude']),
                    "velocity": float(row['speed']),
                    "timestamp": float(row['time']),
                    "acceleration": float(row['acceleration']),
                    "pressure": float(row['pressure']),
                    "state": (row['state_name']).strip(),
                    "position": {'x': float(row['latitude']),
                                'y': float(row['altitude']),
                                'z': float(row['longitude'])},
                    "quaternion": {'x': 0,
                    'y': 0.707,
                    'z': -0.707,
                    'w': 0},

                    "orientation": {'pitch': 30,
                    'roll': 20,
                    'yaw': 20,
                    },

                    "battVolt": float(row['battery_voltage']),
                    "drogVolt": float(row['drogue_voltage']),
                    "temp": float(row['temperature']),
                    "mainVolt": float(row['main_voltage']),
                }
                #print("sending (Sleeptime): " + str(total_sleep_time) )


            #default sleep time
            sleeptime = 0.1
            #ignore negative time
            if (float(row['time']) < 0):
                sleeptime = 0.5
                pass
            if (dat.count != 1):
                if (float(dat[0]['time']) - float(row['time']) == 0):
                    data['timestamp'] = str(float(row['time']) + sleep_offset)
                    sleep_offset += 0.5

                    #default sleep time
                    sleeptime = 0.1
                else:
                    data['timestamp'] = str(float(row['time']) + sleep_offset)
                    sleeptime = float(dat[0]['time']) - float(row['time']) 
                    total_sleep_time += sleeptime 

            #print(data)
            await websocket.send(json.dumps(data))

            await asyncio.sleep(sleeptime)
        except ConnectionClosedOK:
            print("CONNECTION (DASHBOARD) CLOSED", flush = True)
            break

    print ("END OF TRANMISSION", flush = True)

#test run of test data csv to console 
async def rocketry_data_csv_test_console():
    with open('test_data/test-flight-2026-March.csv', 'r', newline='') as csvfile:
        dat = []
        reader = csv.DictReader(csvfile, skipinitialspace=True ,delimiter=',', quotechar='|')
        for row in reader:
            dat.append(row);
    
    #print first x rows of data to check csv
    for idx, row in enumerate(dat):
        if (idx < 30):
            print (dat[idx]['speed'], flush = True)
    #print("reading .csv", dat)
    

if __name__ == "__main__":
    
    print("server start", flush = True)
    asyncio.run(main())
    


    

    #asyncio.run(rocketry_data_csv_test_console())